Repository Omniscient-Job-Project/Omniscient-flutter, pull requests merged in 2024-09, with the labels that each got.

#2 feat : menu , header and footer on main page.
  assets/images/omniscientLogo.png
  lib/main.dart
  lib/widgets/footer.dart
  lib/widgets/header.dart
  lib/widgets/model.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: documentation

#3 feat:mainpage
  lib/core/models/model.dart
  lib/core/services/model.dart
  lib/core/utils/utils.dart
  lib/core/widgets/footer.dart
  lib/core/widgets/header.dart
  lib/core/widgets/model.dart
  lib/features/certificate/models/certificate.dart
  lib/features/certificate/repositories/certificate.dart
  lib/features/certificate/screens/certificate.dart
  lib/features/certificate/widgets/certificate.dart
  lib/features/employment/models/employment.dart
  lib/features/employment/repositories/employment.dart
  lib/features/employment/screens/employment.dart
  lib/features/employment/widgets/employment.dart
  lib/main.dart
Labels: documentation

#4 feat:curation
  lib/core/widgets/header.dart
  lib/features/employment/models/employment.dart
  lib/features/employment/models/job.dart
  lib/features/employment/repositories/employment.dart
  lib/features/employment/repositories/job_repository.dart
  lib/features/employment/screens/employment.dart
  lib/features/employment/screens/job_main_page.dart
  lib/features/employment/widgets/curation_index.dart
  lib/features/employment/widgets/job_card.dart
  lib/features/employment/widgets/search_bar.dart
  lib/main.dart
Labels: documentation

#6 fix:curation
  lib/features/employment/services/job_api_service.dart
Labels: documentation

#7 commit -m "feat : connecting API"
  lib/core/services/api_service.dart
  lib/core/widgets/header.dart
  lib/features/certificate/models/certificateInfo.dart
  lib/features/certificate/models/certificateSchedule.dart
  lib/features/certificate/models/test_job.dart
  lib/features/certificate/repositories/certificateInfo.dart
  lib/features/certificate/repositories/certificateInfoRepository.dart
  lib/features/certificate/repositories/test_job_repository.dart
  lib/features/certificate/screens/certificateInfoPage.dart
  lib/features/certificate/screens/test_jobs_screen.dart
  lib/features/certificate/widgets/certificateInfoCard.dart
  lib/features/certificate/widgets/test_job_list.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  web/index.html
Labels: documentation

#8 commit -m "feat : searching func"
  lib/core/services/api_service.dart
  lib/features/certificate/models/certificateInfo.dart
  lib/features/certificate/repositories/certificateInfoRepository.dart
  lib/features/certificate/screens/certificateInfoPage.dart
  lib/features/certificate/screens/test_jobs_screen.dart
  lib/features/certificate/widgets/certificateInfoCard.dart
  lib/features/certificate/widgets/certificateInfoList.dart
  lib/features/certificate/widgets/test_job_list.dart
Labels: documentation

#9 update: footer
  lib/core/widgets/footer.dart
Labels: 진행중

#10 update: sidebar
  lib/core/widgets/header.dart
  lib/main.dart
Labels: 진행중

#11 feat:login
  lib/features/auth/screens/login_screen.dart
  lib/features/auth/screens/register_screen.dart
  lib/features/auth/services/auth_service.dart
  lib/features/auth/utils/constants.dart
  lib/features/auth/utils/validators.dart
  lib/features/auth/widgets/custom_button.dart
  lib/features/auth/widgets/custom_text_field.dart
  lib/main.dart
  pubspec.yaml
Labels: 진행중

#14 fix: job api
  lib/core/services/api_employ_service.dart
  lib/core/services/api_job_service.dart
  lib/features/employment/models/employment.dart
  lib/features/employment/models/job.dart
  lib/features/employment/repositories/employ_repository.dart
  lib/features/employment/repositories/job_repository.dart
  lib/features/employment/screens/job_main_page.dart
  lib/features/employment/services/employ_api_service.dart
  lib/features/employment/services/job_api_service.dart
  lib/features/employment/viewmodels/employment_viewmodel.dart
  lib/features/employment/widgets/job_card.dart
Labels: 진행중

#15 fix: employ api
  lib/core/services/api_employ_service.dart
  lib/core/services/api_job_service.dart
  lib/features/employment/models/employment.dart
  lib/features/employment/repositories/employ_repository.dart
  lib/features/employment/repositories/job_repository.dart
  lib/features/employment/screens/job_main_page.dart
  lib/features/employment/services/employ_api_service.dart
  lib/features/employment/widgets/employment.dart
Labels: 진행중

#16 fix: 카테고리 필터 적용
  lib/features/employment/screens/job_main_page.dart
Labels: 진행중

#17 git commit -m "feat : my page"
  lib/core/widgets/sidebar_layout.dart
  lib/features/mypage/models/application.dart
  lib/features/mypage/models/certificate.dart
  lib/features/mypage/models/resume.dart
  lib/features/mypage/models/user.dart
  lib/features/mypage/models/user_profile.dart
  lib/features/mypage/models/withdrawal_confirmation.dart
  lib/features/mypage/repositories/application_repository.dart
  lib/features/mypage/repositories/certificate_repository.dart
  lib/features/mypage/repositories/resume_repository.dart
  lib/features/mypage/repositories/user_repository.dart
  lib/features/mypage/repositories/withdrawal_repository.dart
  lib/features/mypage/screens/applications_page.dart
  lib/features/mypage/screens/certificates_page.dart
  lib/features/mypage/screens/home_screen.dart
  lib/features/mypage/screens/profile_page.dart
  lib/features/mypage/screens/resume_page.dart
  lib/features/mypage/screens/withdrawal_page.dart
  lib/features/mypage/widgets/Resume_profile_image.dart
  lib/features/mypage/widgets/application _modal.dart
  lib/features/mypage/widgets/application_item.dart
  lib/features/mypage/widgets/certificates_list.dart
  lib/features/mypage/widgets/common_button.dart
  lib/features/mypage/widgets/profile_image.dart
  lib/main.dart
Labels: 진행중

#18 feat:term
  lib/features/term/models/term_section.dart
  lib/features/term/screens/terms_screen.dart
  lib/features/term/widgets/term_section_widget.dart
  lib/main.dart
Labels: 진행중

#19 fix:term,header
  lib/core/widgets/header.dart
  lib/features/term/screens/terms_screen.dart
Labels: 진행중

#20 git commit -m "feat : notice and faq"
  lib/core/widgets/header.dart
  lib/features/faq/models/faq.dart
  lib/features/faq/repositories/faq_repository.dart
  lib/features/faq/screens/faq_screen.dart
  lib/features/notice/models/notice.dart
  lib/features/notice/repositories/notice_repository.dart
  lib/features/notice/screens/notice_detail_screen.dart
  lib/features/notice/screens/notice_screen.dart
  lib/features/notice/widgets/notice_list_item.dart
  lib/main.dart
Labels: 완료

#21 git commit -m "feat : favorite"
  lib/core/services/api_service.dart
  lib/features/certificate/repositories/certificateInfoRepository.dart
  lib/features/certificate/repositories/test_job_repository.dart
  lib/features/certificate/screens/certificateInfoPage.dart
  lib/features/certificate/widgets/certificateInfoCard.dart
  lib/features/certificate/widgets/certificateInfoList.dart
  lib/features/faq/screens/faq_screen.dart
  lib/features/mypage/models/scrap_item.dart
  lib/features/mypage/repositories/scrap_repository.dart
  lib/features/mypage/screens/scrap_page.dart
  lib/features/mypage/widgets/scarap_info__card.dart
  lib/features/mypage/widgets/scrap_item_card.dart
  lib/features/notice/screens/notice_screen.dart
  lib/main.dart
Labels: 진행중

#22 fix: job service, sidebar
  lib/features/employment/repositories/job_repository.dart
  lib/features/employment/services/job_api_service.dart
Labels: 진행중

#23 fix: sidebar, 회원탈퇴페이지
  lib/core/widgets/sidebar_layout.dart
  lib/features/employment/widgets/job_card.dart
  lib/features/mypage/screens/withdrawal_page.dart
Labels: 진행중

#24 feat: 채용 디테일페이지
  lib/core/widgets/header.dart
  lib/features/employment/widgets/job_detail_card.dart
Labels: 진행중

#25 git commit -m "feat : favorite-employment"
  lib/core/widgets/sidebar_layout.dart
  lib/features/employment/models/employment.dart
  lib/features/employment/models/job.dart
  lib/features/employment/screens/job_main_page.dart
  lib/features/employment/widgets/employment.dart
  lib/features/employment/widgets/job_card.dart
  lib/features/mypage/models/scrap_item.dart
  lib/features/mypage/screens/home_screen.dart
  lib/features/mypage/screens/profile_page.dart
  lib/features/mypage/screens/scrap_page.dart
  lib/features/mypage/widgets/scarap_info__card.dart
  lib/features/mypage/widgets/sidebar.dart
  lib/features/mypage/widgets/summery_grid.dart
Labels: 진행중

#28 feat: 자유게시판
  lib/features/board/models/board.dart
  lib/features/board/services/board_service.dart
  lib/features/board/widgets/board_detail_page.dart
  lib/features/board/widgets/board_list_page.dart
  lib/features/board/widgets/board_post_page.dart
  lib/main.dart
Labels: 진행중
